logo_title: Viki's Blog
style: black

favicon: /favicon.ico

menu:
  About: /about
  Github: https://github.com/vikiboss

# 做了域名限制，请改成自己的 KEY
valine:
  appId: t8FRTzDWlzyWdMbxy6QqUleO-gzGzoHsz
  appKey: MCfD6bwFzcWz7364yKp49WBU

highlight:
  enable: false